-- The scheduled reminders become first-class mail.
--
-- The six reminder families in supabase/functions/remind built their own subjects and bodies
-- and POSTed them straight to Resend, never touching public.emails. Four consequences, all
-- from the same cause: they could not be silenced, they left no row in the mail log, they got
-- no delivery reconciliation, and they were missing from the data export DESIGN.md says counts
-- every message a scholar was sent.
--
-- Routing them through the table fixes all four, and the cron needs a way in. It runs as
-- `service_role` with no auth.uid(), so it cannot call public.queue_email.
--
-- Two of the six reuse an existing template rather than gaining one, because chasing a thing
-- is the same subscription as being told about it: the editor-waiting reminder IS
-- SubmissionsNeedEditors, and CompensationPending defers to CompensationRequested. Only the
-- unpaid-charge reminder is consequential — nobody opts out of being told they owe money, and
-- that reminder exists precisely because the first notice can be missed.

--------------------------------------
-- RPC
--
-- queue_reminder_email: the scheduled reminders' way into the mail pipeline.
--
-- A third queueing function rather than a branch inside queue_email, because the caller is
-- not a person. The reminder cron runs as `service_role` with no `auth.uid()`, so it fails
-- queue_email's first line; loosening that check would mean the function that every
-- user-facing producer goes through no longer requires a caller, which is a worse trade than
-- a small sibling.
--
-- It keeps queue_email's actual safety property intact: it accepts no address, no subject and
-- no body. The recipient is resolved from a scholar id, skipped without a verified contact
-- email, and skipped again if the preference is off -- so a reminder is silenceable by the
-- same mark on the same template as the notice it chases. `sender` is null because nobody
-- sent it, which is the honest record and matches reconcile_ledger's own notifications.
--
-- `reply_to` is left null deliberately. The cron used to set it to stewards@ explicitly, and
-- null already resolves to exactly that (see send_email), so the reminders keep the reply
-- path they had -- the one thing about them most likely to be answered with a question.
create or replace function public.queue_reminder_email (
	_event text,
	_args text[],
	_scholar uuid
) returns integer language plpgsql security definer
set
	"search_path" to 'public',
	'pg_temp' as $$
declare
	_count integer;
begin
	if _event is null or _event = '' then
		raise exception 'An event is required';
	end if;
	-- The same refusal queue_email makes, for the same reason: VerifyEmail renders an
	-- argument as a clickable link, so it is queued only by request_email_verification.
	if _event = 'VerifyEmail' then
		raise exception 'VerifyEmail is queued only by request_email_verification';
	end if;

	insert into public.emails (event, scholar, sender, venue, email, subject, message, args)
	select _event, s.id, null, null, s.email, null, null, to_jsonb(_args)
	from public.scholars s
	where s.id = _scholar
		and s.email is not null
		and public.notification_allowed(s.id, _event);

	get diagnostics _count = row_count;
	return _count;
end;
$$;

alter function public.queue_reminder_email (text, text[], uuid) OWNER to "postgres";

-- Explicitly revoked, not merely un-granted: Supabase's ALTER DEFAULT PRIVILEGES hands anon
-- and authenticated EXECUTE on every function created in `public` at creation time, and
-- `revoke ... from public` does not take those back. See 20260831000000. Leaving this open
-- would hand any signed-in user a way to send branded mail to any scholar, with no caller
-- recorded against it -- strictly worse than queue_email, which at least stamps `sender`.
revoke
execute on function public.queue_reminder_email (text, text[], uuid)
from
	public,
	anon,
	authenticated;

grant
execute on function public.queue_reminder_email (text, text[], uuid) to service_role;

--------------------------------------
-- Seed
--
-- GENERATED by `node scripts/notification-seeds.js`; src/email/templates.unit.ts asserts this
-- matches the registry.
insert into public.notification_preferences (key, default_on) values
	('AvailabilityReminder', true),
	('CompensationRequested', true),
	('NewVolunteer', true),
	('SubmissionsNeedEditors', true),
	('SubmissionsReady', true),
	('ThanksPendingReview', true),
	('ThanksReceived', true),
	('ThanksShared', true),
	('TransactionApproved', true),
	('TransactionsPending', true),
	('VenueApproved', true)
on conflict (key) do update set default_on = excluded.default_on;

insert into public.optional_emails (event, preference) values
	('AvailabilityReminder', 'AvailabilityReminder'),
	('CompensationPending', 'CompensationRequested'),
	('CompensationRequested', 'CompensationRequested'),
	('NewVolunteer', 'NewVolunteer'),
	('ProposalDeclined', 'VenueApproved'),
	('SubmissionNeedsEditor', 'SubmissionsNeedEditors'),
	('SubmissionsNeedEditors', 'SubmissionsNeedEditors'),
	('SubmissionsReady', 'SubmissionsReady'),
	('ThanksPendingReview', 'ThanksPendingReview'),
	('ThanksReceived', 'ThanksReceived'),
	('ThanksShared', 'ThanksShared'),
	('TransactionApproved', 'TransactionApproved'),
	('TransactionsPending', 'TransactionsPending'),
	('VenueApproved', 'VenueApproved')
on conflict (event) do update set preference = excluded.preference;

delete from public.optional_emails where event not in ('AvailabilityReminder', 'CompensationPending', 'CompensationRequested', 'NewVolunteer', 'ProposalDeclined', 'SubmissionNeedsEditor', 'SubmissionsNeedEditors', 'SubmissionsReady', 'ThanksPendingReview', 'ThanksReceived', 'ThanksShared', 'TransactionApproved', 'TransactionsPending', 'VenueApproved');
delete from public.notification_preferences where key not in ('AvailabilityReminder', 'CompensationRequested', 'NewVolunteer', 'SubmissionsNeedEditors', 'SubmissionsReady', 'ThanksPendingReview', 'ThanksReceived', 'ThanksShared', 'TransactionApproved', 'TransactionsPending', 'VenueApproved');
